language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

env:
  global:
    - DB_USERNAME="postgres"
    - DB_PASSWORD=""

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - travis_retry composer self-update
  - cp .env.example .env

install:
  - travis_retry composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: true
