language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

env:
  global:
    - DB_USERNAME="postgres"
    - DB_PASSWORD=""

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - psql -c 'create database movie_night_test;' -U postgres

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate --ansi

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_failure:
- cat storage/logs/laravel*.log

after_script:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: true
